'use strict'

// Offline license manager: 15-day trial + Ed25519-signed lifetime token.
//
// - Trial is tracked in a durable store (userData/license.json) plus a backup
//   anchor (~/.transcriptai-license.json) so casually deleting one file does not
//   reset the trial. We take the EARLIEST firstSeenAt across both.
// - Fail-closed: if a store exists but firstSeenAt is missing/unparseable, or the
//   clock looks rolled back/forward, the trial is treated as expired.
// - A purchased token is a base64url(payload) + "." + base64url(ed25519 signature)
//   string, signed by the seller's private key and verified here with the embedded
//   public key. No network needed. (Determined users can bypass a local check —
//   this is a strong deterrent, not unbreakable DRM.)

const { app } = require('electron')
const fs = require('fs')
const os = require('os')
const path = require('path')
const crypto = require('crypto')

const TRIAL_DAYS = 15
const PRICE = '$18.83'                 // promotional launch price (what they pay)
const ORIGINAL_PRICE = '$100.83'       // anchor price, shown struck-through
const PROMO_LABEL = 'Launch offer for early users'
// kalam-plus product page (where users learn about + buy TranscriptAI).
const PURCHASE_URL = 'https://kalam-plus.com/#transcriptai'
const CLOCK_SKEW_MS = 5 * 60 * 1000
const DAY_MS = 24 * 60 * 60 * 1000

// Public key (verify-only; safe to ship). Generated by scripts/license/generate-keypair.js.
const LICENSE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEA8qmwr1HrifcV3BLLIF15JxYNH3+R1shH/MY5TILABno=
-----END PUBLIC KEY-----`

let _publicKey = null
function publicKey() {
  if (!_publicKey) _publicKey = crypto.createPublicKey(LICENSE_PUBLIC_KEY_PEM)
  return _publicKey
}

function primaryPath() { return path.join(app.getPath('userData'), 'license.json') }
function backupPath() { return path.join(os.homedir(), '.transcriptai-license.json') }

function readJson(p) {
  try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch { return null }
}
function writeJsonSafe(p, obj) {
  try { fs.writeFileSync(p, JSON.stringify(obj, null, 2)); return true } catch { return false }
}

function b64urlToBuf(s) {
  let v = String(s).replace(/-/g, '+').replace(/_/g, '/')
  while (v.length % 4) v += '='
  return Buffer.from(v, 'base64')
}

// Verify a token's signature with the embedded public key.
// Returns { valid, payload?, expired? }.
function verifyToken(token) {
  if (typeof token !== 'string') return { valid: false }
  const t = token.trim()
  const dot = t.indexOf('.')
  if (dot <= 0 || dot >= t.length - 1) return { valid: false }
  const payloadB64 = t.slice(0, dot)
  const sigB64 = t.slice(dot + 1)

  let ok = false
  try {
    ok = crypto.verify(null, Buffer.from(payloadB64, 'utf8'), publicKey(), b64urlToBuf(sigB64))
  } catch { return { valid: false } }
  if (!ok) return { valid: false }

  let payload = null
  try { payload = JSON.parse(b64urlToBuf(payloadB64).toString('utf8')) } catch { return { valid: false } }

  // Lifetime tokens have no exp; support optional exp for future subscription tokens.
  if (payload && payload.exp) {
    const expMs = Date.parse(payload.exp)
    if (Number.isFinite(expMs) && Date.now() > expMs) return { valid: false, expired: true, payload }
  }
  return { valid: true, payload }
}

let state = null

function persist() {
  if (!state) return
  writeJsonSafe(primaryPath(), {
    firstSeenAt: state.firstSeenAt,
    lastSeenAt: state.lastSeenAt,
    token: state.token || null,
  })
  if (state.firstSeenAt) writeJsonSafe(backupPath(), { firstSeenAt: state.firstSeenAt })
}

// Initialize on app startup. Sets the trial start on first run; detects tampering.
function init() {
  const primary = readJson(primaryPath())
  const backup = readJson(backupPath())
  const now = Date.now()

  const fsCandidates = [primary && primary.firstSeenAt, backup && backup.firstSeenAt]
    .map(s => Date.parse(s)).filter(Number.isFinite)
  let firstSeenMs = fsCandidates.length ? Math.min(...fsCandidates) : null

  let tampered = false
  // A store existed but no usable firstSeenAt → corruption/tamper → fail closed.
  if ((primary || backup) && firstSeenMs === null) tampered = true
  // Clock rolled back: last recorded run is in the future beyond skew.
  const lastSeenMs = primary ? Date.parse(primary.lastSeenAt) : NaN
  if (Number.isFinite(lastSeenMs) && lastSeenMs > now + CLOCK_SKEW_MS) tampered = true
  // firstSeenAt in the future → tamper.
  if (firstSeenMs !== null && firstSeenMs > now + CLOCK_SKEW_MS) tampered = true

  if (firstSeenMs === null && !tampered) firstSeenMs = now // fresh trial

  state = {
    firstSeenAt: firstSeenMs !== null ? new Date(firstSeenMs).toISOString() : null,
    lastSeenAt: new Date(now).toISOString(),
    token: primary && primary.token ? primary.token : null,
    tampered,
  }
  persist()
  return getStatus()
}

// Returns { state: 'trial'|'expired'|'licensed', daysRemaining, trialDays, price, purchaseUrl, ... }
function getStatus() {
  if (!state) {
    return { state: 'trial', daysRemaining: TRIAL_DAYS, trialDays: TRIAL_DAYS, price: PRICE, originalPrice: ORIGINAL_PRICE, promoLabel: PROMO_LABEL, purchaseUrl: PURCHASE_URL }
  }

  if (state.token) {
    const v = verifyToken(state.token)
    if (v.valid) {
      return {
        state: 'licensed',
        daysRemaining: 0,
        trialDays: TRIAL_DAYS,
        price: PRICE,
        originalPrice: ORIGINAL_PRICE,
        promoLabel: PROMO_LABEL,
        purchaseUrl: PURCHASE_URL,
        licensedTo: (v.payload && v.payload.name) || null,
        plan: (v.payload && v.payload.type) || 'lifetime',
      }
    }
    // Invalid/expired stored token → fall through to trial/expired.
  }

  let daysRemaining = 0
  if (!state.tampered && state.firstSeenAt) {
    const firstMs = Date.parse(state.firstSeenAt)
    if (Number.isFinite(firstMs)) {
      const elapsedDays = Math.floor((Date.now() - firstMs) / DAY_MS)
      daysRemaining = Math.max(0, TRIAL_DAYS - elapsedDays)
    }
  }
  return {
    state: daysRemaining > 0 ? 'trial' : 'expired',
    daysRemaining,
    trialDays: TRIAL_DAYS,
    price: PRICE,
    originalPrice: ORIGINAL_PRICE,
    promoLabel: PROMO_LABEL,
    purchaseUrl: PURCHASE_URL,
  }
}

// Validate and store a pasted token. Returns { ok, status?, error? }.
function activate(token) {
  const v = verifyToken(token)
  if (!v.valid) {
    return { ok: false, error: v.expired ? 'This license token has expired.' : 'Invalid license token. Please check and try again.' }
  }
  if (!state) init()
  state.token = String(token).trim()
  persist()
  return { ok: true, status: getStatus() }
}

module.exports = { init, getStatus, activate, verifyToken, PURCHASE_URL, PRICE, TRIAL_DAYS }
