/**
 * GENERATED BY scripts/scaffold.ts -- placeholder derived from docs/spec.md.
 */
export const transcriptionShortClipRequestSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://transcriptai.local/schemas/transcription-short-clip-request.schema.json",
  "title": "TranscriptionShortClipRequest",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "clipId",
    "sourcePath"
  ],
  "properties": {
    "clipId": {
      "type": "string",
      "format": "uuid",
      "description": "Identifier for the existing transcription job that produced an empty result."
    },
    "sourcePath": {
      "type": "string",
      "description": "Absolute path to the normalized audio file replayed by the fallback pipeline."
    },
    "forcedLanguage": {
      "type": "string",
      "description": "Optional ISO language code to override detection; defaults to existing desktop flag.",
      "minLength": 2,
      "maxLength": 5
    },
    "requestedBy": {
      "type": "string",
      "description": "Actor initiating the fallback (ui|api|automation).",
      "enum": [
        "ui",
        "api",
        "automation"
      ]
    }
  }
} as const

export type TranscriptionShortClipRequest = {
  clipId: string  // Identifier for the existing transcription job that produced an empty result.
  sourcePath: string  // Absolute path to the normalized audio file replayed by the fallback pipeline.
  forcedLanguage?: string  // Optional ISO language code to override detection; defaults to existing desktop flag.
  requestedBy?: "ui" | "api" | "automation"  // Actor initiating the fallback (ui|api|automation).
}
