/**
 * GENERATED BY scripts/scaffold.ts -- placeholder derived from docs/spec.md.
 */
export const transcriptionShortClipResponseSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://transcriptai.local/schemas/transcription-short-clip-response.schema.json",
  "title": "TranscriptionShortClipResponse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "ok",
    "jobId",
    "clipId",
    "status",
    "queuedAt"
  ],
  "properties": {
    "ok": {
      "type": "boolean",
      "description": "Indicates whether the request was accepted or the last chunk processed successfully."
    },
    "jobId": {
      "type": "string",
      "description": "Deterministic identifier for the fallback job (uuid-v4).",
      "format": "uuid"
    },
    "clipId": {
      "type": "string",
      "format": "uuid",
      "description": "Echoes the originating clip identifier."
    },
    "status": {
      "type": "string",
      "enum": [
        "queued",
        "processing",
        "succeeded",
        "failed"
      ],
      "description": "Current lifecycle state for the fallback attempt."
    },
    "queuedAt": {
      "type": "string",
      "format": "date-time",
      "description": "RFC 3339 timestamp of when the fallback job entered the queue."
    },
    "completedAt": {
      "type": "string",
      "format": "date-time",
      "description": "RFC 3339 timestamp captured once the fallback finishes."
    },
    "errorMessage": {
      "type": "string",
      "description": "Human-readable failure summary returned when status=failed."
    },
    "estimatedLatencyMs": {
      "type": "integer",
      "description": "Estimated processing latency communicated during queue acknowledgement."
    }
  }
} as const

export type TranscriptionShortClipResponse = {
  ok: boolean  // Indicates whether the request was accepted or the last chunk processed successfully.
  jobId: string  // Deterministic identifier for the fallback job (uuid-v4).
  clipId: string  // Echoes the originating clip identifier.
  status: "queued" | "processing" | "succeeded" | "failed"  // Current lifecycle state for the fallback attempt.
  queuedAt: string  // RFC 3339 timestamp of when the fallback job entered the queue.
  completedAt?: string  // RFC 3339 timestamp captured once the fallback finishes.
  errorMessage?: string  // Human-readable failure summary returned when status=failed.
  estimatedLatencyMs?: number  // Estimated processing latency communicated during queue acknowledgement.
}
