export { default as Capture } from './Upload'
export { RecordingsView as Transcripts } from '../modules/recordings/RecordingsView'
export { default as Settings } from './Settings'
export { default as Dashboard } from './Dashboard'
export { default as LiveMode } from './LiveMode'
